swagger: "2.0"
info:
  title: User Regstration
  description: Register a user
  version: 1.0.0
host: food.homecater.com
schemes:
  - https
paths:
  /user/register:
    post:
      summary: Register user into food catering service
      operationId: 'registerUser'
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: "user"
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/Status"
        "400":
          description: "Invalid Request"


definitions:
  User:
    type: object
    properties:
      username:
        type: "string"
      password:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      type:
        type: "string"
      address1:
        type: "string"
      address2:
        type: "string"
      city:
        type: "string"
      state:
        type: "string"
      zip:
        type: "string"
  Status:
    type: object
    properties:
      status:
        type: "string"
      message:
        type: "string"



